### ISSUE TITLE
iOS/iPadOS failed to restart screen share

### ISSUE THREAD

**Issue by v57** [livekit-examples/swift-example#37]
When I connect to room and start screen sharing - it works. But when I stop screen sharing and then start it back - it stays in loading state. After leaving the room and joining it back, it works (also only once)

### Starting screen share

![broadcast](https://uploads.linear.app/65f9603c-a265-4a1f-8af0-4c2243b87ade/0c80e3b9-1b65-4774-9b9a-e614bc5a592d/07bc7d2e-4fa7-437c-af1e-6828082ade68?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1Zjk2MDNjLWEyNjUtNGExZi04YWYwLTRjMjI0M2I4N2FkZS8wYzgwZTNiOS0xYjY1LTQ3NzQtOWI5YS1lNjE0YmM1YTU5MmQvMDdiYzdkMmUtNGZhNy00MzdjLWFmMWUtNjgyODA4MmFkZTY4IiwiaWF0IjoxNzA4Njk5ODk2LCJleHAiOjMzMjc5MjU5ODk2fQ.Lo7-AUX9r5pjpoimALY7bkk40uOL7Ek8UgctwmqAJJw)

### Restarting screen share

![broadcast-failed](https://uploads.linear.app/65f9603c-a265-4a1f-8af0-4c2243b87ade/7808a836-ee68-4e30-81a5-2a654d215462/e9e62fa0-0157-4017-b200-10004e27c1e5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1Zjk2MDNjLWEyNjUtNGExZi04YWYwLTRjMjI0M2I4N2FkZS83ODA4YTgzNi1lZTY4LTRlMzAtODFhNS0yYTY1NGQyMTU0NjIvZTllNjJmYTAtMDE1Ny00MDE3LWIyMDAtMTAwMDRlMjdjMWU1IiwiaWF0IjoxNzA4Njk5ODk2LCJleHAiOjMzMjc5MjU5ODk2fQ.lKgWPbm78kryybTdwD9glAGetGMPIaArhLHvEPnOEDs)

**Comment by royatanu94** [comment]
hi, 
Are you able to fix this?
TIA

**Comment by hiroshihorie** [comment]
I think https://github.com/livekit/client-sdk-swift/pull/424 fixes this.
