### ISSUE TITLE
Screenshare not working for 2nd time onwards in IOS & Video sharing not visible at IOS

### ISSUE THREAD

**Issue by royatanu94** [livekit-examples/swift-example#39]
Hi,
I was using swift example app to test screenshare. I have seen an issue when you share your screen for the first time then broadcast app will start and screenshare will work fine, when you stop broadcast app will stop. But if you try to share screen for the second time it will not work. It works only for 1st time, next time onwards screenshare won't work.

Its also seen that if we 1st join room > share screen > stop share screen > publish user video using any codec, in IOS UI user video is not visible but its visible in other participants UI.

@hiroshihorie  Any help is really appreciated

TIA

**Comment by mokuzuu** [comment]
@royatanu94  I experienced this issue as well. Have you found the solution for this?

**Comment by hiroshihorie** [comment]
I think https://github.com/livekit/client-sdk-swift/pull/424 fixes this.
